Repository pr-org/pr_test, pull requests merged in 2020-03, with the labels that each got.

#1 1st PR
  README.md
Labels: enhancement, good first issue

#2 2nd PR
  README.md
Labels: enhancement

#4 3rd PR
  README.md
Labels: my-lable

#6 4th PR
  README.md
Labels: bug, enhancement, my-lable

#9 5 PR
  README.md
Labels: bug, enhancement, good first issue, help wanted, my-lable
